// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcrlqcczvmknuqcfjjlj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjcmxxY2N6dm1rbnVxY2ZqamxqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4OTU0ODMsImV4cCI6MjA3NDQ3MTQ4M30.omeLJbk1iyNLAjHtKxpcH4QlrBoLT_ooPUpuEDysOOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});